### ISSUE TITLE
Package a session with system dependencies

### ISSUE THREAD

**Issue by nuest** [o2r-project/containerit#33] opened 2016-12-12 15:48 UTC
extends #6 

The session loads rgdal and proj packages and adds the required libraries in the Dockerfile.

Use two approaches and then compare:

1. `rsysreqs`
1. https://github.com/rstudio/shinyapps-package-dependencies (in the Dockerfile: clone the repo then execute the respective install script)

**Comment by MatthiasHinz** [comment] 2017-01-13 15:01
We could possibly use either of them or even both. I like that in Shiny also provide short test scripts, but the repository does not support so many packages at the moment (e.g. rgdal and maptools are not yet there). 

`sysreqs` has the advantage that it allows to create OS-specific installation commands, that we could directly paste to the Dockerfile. Also we could take advantage of the [public database API](https://sysreqs.r-hub.io/) or the package, but there are limitations: Actually it's hard to determine how many packages are supported by `sysreq`, because the API only allows to list the the system dependencies, which are about 60. Also, if no dependencies are found, it cannot be determined whether the package is unknown or whether there are no requirements. The only user-side method of the current _`sysreq`-package_ determines system dependencies from a given DESCRIPTION file, which is not exactly what we want, but even though there are workarounds for this.

Some requests I tried out with the sysreq DB (which is the backend for the package):
https://sysreqs.r-hub.io/list
https://sysreqs.r-hub.io/pkg/rgdal/linux-x86_64-ubuntu-gcc
https://sysreqs.r-hub.io/pkg/sp/linux-x86_64-ubuntu-gcc
https://sysreqs.r-hub.io/pkg/FALSEPACKAGE/linux-x86_64-ubuntu-gcc

**Comment by edzer** [comment] 2017-01-13 15:06
for the shiny case: `libgdal-dev` is in the basic Dockerfile, so `rgdal` should install without problems; the packages listed in the packages directory are only those that need _additional_ system requirements, afaics.

**Comment by MatthiasHinz** [comment] 2017-01-13 16:02
So, using shiny-dependencies we need to install all dependencies from the basic Dockerfile, even though they may be needless for reproducing a specific session or workspace.

From the approach, I would favor `sysreqs`, because it can tell exactly the requirements for each package. 

We may consider Shiny if it turns out to be more reliable (which is hard to determine at the moment), or if we want to re-use these test scripts. If the shiny dependencies also include system requirements for frequently used non-CRAN packages, it may also be interesting.

**Comment by MatthiasHinz** [comment] 2017-01-23 19:08
Works for sysreqs + rocker now:

Test output:

```
local sessionInfo: 

R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8    
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] methods   stats     graphics  grDevices utils     datasets  base     

other attached packages:
[1] proj4_1.0-8 rgdal_1.2-5 sp_1.2-4   

loaded via a namespace (and not attached):
[1] codetools_0.2-15 grid_3.3.2       lattice_0.20-34 

------------------------------------
reproduced sessionInfo in docker: 

R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] methods   stats     graphics  grDevices utils     datasets  base     

other attached packages:
[1] proj4_1.0-8 rgdal_1.2-5 sp_1.2-4   

loaded via a namespace (and not attached):
[1] codetools_0.2-15 grid_3.3.2       lattice_0.20-34 

Dockerfile: 

FROM rocker/r-ver:3.3.2
MAINTAINER "matthiashinz"
RUN ["apt-get", "update", "-qq"]
RUN ["apt-get", "install", "-y", "gdal-bin", "libgdal-dev", "libgeos-dev", "libproj-dev"]
RUN ["install2.r", "-r 'https://cran.rstudio.com'", "proj4", "rgdal", "sp", "codetools", "lattice"]
CMD ["R"]
```

**Comment by MatthiasHinz** [comment] 2017-01-26 11:09
to close this:

- create issue regarding locales
- create issue on problems with shinyapps (baseimage etc.)

**Closed** 2017-01-26 17:43 UTC
